services:
  app:
    build:
      target: production
    environment:
      - APP_ENV=production

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done'"
    restart: unless-stopped

  postgres:
    command:
      - postgres
      - -c
      - shared_buffers=128MB
      - -c
      - effective_cache_size=256MB
      - -c
      - work_mem=4MB
      - -c
      - max_connections=30
    deploy:
      resources:
        limits:
          memory: 256M

  redis:
    command: redis-server --appendonly yes --maxmemory 64mb --maxmemory-policy allkeys-lru
    deploy:
      resources:
        limits:
          memory: 96M
